In [1]:
#import dependecies

import pandas as pd

In [2]:
#give a name to data file

data_one = "Resources/JC-202001-citibike-tripdata.csv"

In [3]:
#create dataframe

data_one_df = pd.read_csv(data_one)

In [4]:
#check the data in df

data_one_df.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2

In [5]:
#checking information about df

data_one_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26020 entries, 0 to 26019
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   tripduration             26020 non-null  int64
 1   starttime                26020 non-null  object
 2   stoptime                 26020 non-null  object
 3   start station id         26020 non-null  int64
 4   start station name       26020 non-null  object
 5   start station latitude   26020 non-null  float64
 6   start station longitude  26020 non-null  float64
 7   end station id           26020 non-null  int64
 8   end station name         26020 non-null  object
 9   end station latitude     26020 non-null  float64
 10  end station longitude    26020 non-null  float64
 11  bikeid                   26020 non-null  int64
 12  usertype                 26020 non-null  object
 13  birth year               26020 non-null  int64
 14  gender                   26020 non-null  int64
dtypes: float64(4), int64(6), object(5)
memory usage: 3.0+ MB

In [6]:
#finding rows with NaN

#is_NaN = data_one_df.isnull()
#rows_has_NaN = is_NaN.any(axis = 1)
#rows_with_NaN = data_one_df[rows_has_NaN]
#rows_with_NaN

In [7]:
#rechecking by dropping NaN's

data_one_df.dropna(how = 'any', inplace = True)

In [8]:
#rechecking information about df

data_one_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26020 entries, 0 to 26019
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   tripduration             26020 non-null  int64
 1   starttime                26020 non-null  object
 2   stoptime                 26020 non-null  object
 3   start station id         26020 non-null  int64
 4   start station name       26020 non-null  object
 5   start station latitude   26020 non-null  float64
 6   start station longitude  26020 non-null  float64
 7   end station id           26020 non-null  int64
 8   end station name         26020 non-null  object
 9   end station latitude     26020 non-null  float64
 10  end station longitude    26020 non-null  float64
 11  bikeid                   26020 non-null  int64
 12  usertype                 26020 non-null  object
 13  birth year               26020 non-null  int64
 14  gender                   26020 non-null  int64
dtypes: float64(4), int64(6), object(5)
memory usage: 3.2+ MB

In [9]:
#download all data

data_two = "Resources/JC-202002-citibike-tripdata.csv"
data_three = "Resources/JC-202003-citibike-tripdata.csv"
data_four = "Resources/JC-202004-citibike-tripdata.csv"
data_five = "Resources/JC-202005-citibike-tripdata.csv"
data_six = "Resources/JC-202006-citibike-tripdata.csv"
data_seven = "Resources/JC-202007-citibike-tripdata.csv"
data_eight = "Resources/JC-202008-citibike-tripdata.csv"
data_nine = "Resources/JC-202009-citibike-tripdata.csv"
data_ten = "Resources/JC-202010-citibike-tripdata.csv"
data_eleven = "Resources/JC-202011-citibike-tripdata.csv"
data_twelve = "Resources/JC-202012-citibike-tripdata.csv"

In [10]:
#put all data in df

data_two_df = pd.read_csv(data_two)
data_three_df = pd.read_csv(data_three)
data_four_df = pd.read_csv(data_four)
data_five_df = pd.read_csv(data_five)
data_six_df = pd.read_csv(data_six)
data_seven_df = pd.read_csv(data_seven)
data_eight_df = pd.read_csv(data_eight)
data_nine_df = pd.read_csv(data_nine)
data_ten_df = pd.read_csv(data_ten)
data_eleven_df = pd.read_csv(data_eleven)
data_twelve_df = pd.read_csv(data_twelve)

In [11]:
#finding rows with NaN in all data one by one

#is_NaN = data_twelve_df.isnull()
#rows_has_NaN = is_NaN.any(axis = 1)
#rows_with_NaN = data_twelve_df[rows_has_NaN]
#rows_with_NaN

In [14]:
#merge all data 
merged_df = pd.concat([data_one_df, data_two_df, data_three_df, data_four_df, data_five_df, data_six_df, data_seven_df, data_eight_df, data_nine_df, data_ten_df, data_eleven_df, data_twelve_df])

In [15]:
#check indexes in new df
merged_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0
11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0
11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1
11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0
11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1

In [17]:
#reset indexes
merged_df = merged_df.reset_index()

In [18]:
#check indexes again
merged_df

,index,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2
1,1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2
2,2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1
3,3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0
4,4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336797,11689,1750,2020-12-31 23:07:44.0030,2020-12-31 23:36:54.4710,3199,Newport Pkwy,40.728745,-74.032108,3199,Newport Pkwy,40.728745,-74.032108,40440,Customer,1969,0
336798,11690,1519,2020-12-31 23:18:00.2630,2020-12-31 23:43:19.8590,3184,Paulus Hook,40.714145,-74.033552,3195,Sip Ave,40.730897,-74.063913,46340,Customer,1969,0
336799,11691,1761,2020-12-31 23:31:09.4620,2021-01-01 00:00:31.3290,3195,Sip Ave,40.730897,-74.063913,3270,Jersey & 6th St,40.725289,-74.045572,40907,Customer,1998,1
336800,11692,637,2020-12-31 23:35:45.4640,2020-12-31 23:46:22.7300,3681,Grand St,40.715178,-74.037683,3199,Newport Pkwy,40.728745,-74.032108,42250,Customer,1969,0
336801,11693,1607,2020-12-31 23:48:34.5750,2021-01-01 00:15:22.3090,3267,Morris Canal,40.712419,-74.038526,3267,Morris Canal,40.712419,-74.038526,48742,Subscriber,1982,1